// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cholupdate
arma::mat cholupdate(const arma::mat& L, const arma::vec& x);
RcppExport SEXP RcppTIB_cholupdate(SEXP LSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    __result = Rcpp::wrap(cholupdate(L, x));
    return __result;
END_RCPP
}
// forwardsolve
arma::cx_mat forwardsolve(const arma::cx_mat& L, const arma::cx_mat& x);
RcppExport SEXP RcppTIB_forwardsolve(SEXP LSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type x(xSEXP);
    __result = Rcpp::wrap(forwardsolve(L, x));
    return __result;
END_RCPP
}
// solvetibM
arma::cx_mat solvetibM(const arma::cx_vec& M, const arma::cx_mat& x);
RcppExport SEXP RcppTIB_solvetibM(SEXP MSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cx_vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type x(xSEXP);
    __result = Rcpp::wrap(solvetibM(M, x));
    return __result;
END_RCPP
}
// timestibN
arma::cx_mat timestibN(const arma::cx_vec& N, const arma::cx_mat& x);
RcppExport SEXP RcppTIB_timestibN(SEXP NSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cx_vec& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::cx_mat& >::type x(xSEXP);
    __result = Rcpp::wrap(timestibN(N, x));
    return __result;
END_RCPP
}
// sptib_cpp
Rcpp::List sptib_cpp(const arma::cx_vec& lambda);
RcppExport SEXP RcppTIB_sptib_cpp(SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cx_vec& >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(sptib_cpp(lambda));
    return __result;
END_RCPP
}
