# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholupdate <- function(L, x) {
    .Call('RcppTIB_cholupdate', PACKAGE = 'RcppTIB', L, x)
}

forwardsolve <- function(L, x) {
    .Call('RcppTIB_forwardsolve', PACKAGE = 'RcppTIB', L, x)
}

solvetibM <- function(M, x) {
    .Call('RcppTIB_solvetibM', PACKAGE = 'RcppTIB', M, x)
}

timestibN <- function(N, x) {
    .Call('RcppTIB_timestibN', PACKAGE = 'RcppTIB', N, x)
}

sptib_cpp <- function(lambda) {
    .Call('RcppTIB_sptib_cpp', PACKAGE = 'RcppTIB', lambda)
}

